[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = [
  "npm run prisma:generate --workspace=@bina/api",
  "npm run build --workspace=@bina/api"
]

[start]
cmd = "npm run --workspace=@bina/api prisma:migrate-deploy && npm run --workspace=@bina/api seed && npm run start --workspace=@bina/api"
